/*******************************************************************************
 * Interface_NavMeshPathObject generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
interface Interface_NavMeshPathObject extends Interface
    abstract
    native(AI);
